#!/usr/bin/env node

/**
 * Simple development server for Sisters Cafe
 * Serves static files and API endpoints
 */

import http from 'http';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import url from 'url';
import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

// Get __dirname equivalent in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
dotenv.config();

// In-memory order storage for development
let orders = [];

// Email configuration
const RESTAURANT_EMAIL = 'sisters806@gmail.com';

// Create email transporter
let emailTransporter;
try {
  emailTransporter = nodemailer.createTransporter({
    service: 'gmail',
    auth: {
      user: process.env.EMAIL_USER || 'sisters806@gmail.com',
      pass: process.env.EMAIL_APP_PASSWORD || 'BAseBAll!#80'
    }
  });
} catch (error) {
  console.log('⚠️ Email transporter setup failed, will show previews only');
  emailTransporter = null;
}

// Email notification function - SENDS REAL EMAILS to sisters806@gmail.com
async function sendOrderNotificationEmail(order) {
  const orderTotal = (order.amount_total / 100).toFixed(2);
  const orderDate = new Date(order.created_at).toLocaleString();
  
  // Create HTML email content
  const emailContent = `
    <h2>🍽️ New Order Received - Sisters Cafe</h2>
    
    <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
      <h3>Order Details</h3>
      <p><strong>Order ID:</strong> ${order.id}</p>
      <p><strong>Customer:</strong> ${order.customer_name}</p>
      <p><strong>Phone:</strong> <a href="tel:${order.customer_phone}">${order.customer_phone}</a></p>
      <p><strong>Email:</strong> <a href="mailto:${order.customer_email}">${order.customer_email}</a></p>
      <p><strong>Pickup Time:</strong> ${order.pickup_time}</p>
      <p><strong>Total Amount:</strong> $${orderTotal}</p>
      <p><strong>Order Time:</strong> ${orderDate}</p>
      <p><strong>Payment Status:</strong> ✅ ${order.status.toUpperCase()}</p>
    </div>
    
    ${order.items && order.items.length > 0 ? `
      <div style="background: #e9ecef; padding: 20px; border-radius: 8px; margin: 20px 0;">
        <h3>Order Items</h3>
        <ul style="margin: 0; padding-left: 20px;">
          ${order.items.map(item => `<li>${item}</li>`).join('')}
        </ul>
      </div>
    ` : ''}
    
    ${order.notes ? `
      <div style="background: #fff3cd; padding: 15px; border-radius: 8px; margin: 20px 0;">
        <h4>Special Instructions:</h4>
        <p style="margin: 0;">${order.notes}</p>
      </div>
    ` : ''}
    
    <div style="background: #d1ecf1; padding: 20px; border-radius: 8px; margin: 20px 0;">
      <h3>Next Steps:</h3>
      <ol style="margin: 0; padding-left: 20px;">
        <li>Prepare the order for pickup at: <strong>${order.pickup_time}</strong></li>
        <li>Contact customer if needed: <a href="tel:${order.customer_phone}" style="color: #007bff;">${order.customer_phone}</a></li>
        <li>Email customer at: <a href="mailto:${order.customer_email}" style="color: #007bff;">${order.customer_email}</a></li>
        <li>Contact customer when order is ready for pickup</li>
      </ol>
    </div>
    
    <hr>
    <p style="color: #6c757d; font-size: 12px;">
      This email was automatically generated by Sisters Cafe online ordering system.<br>
      Stripe Session ID: ${order.stripe_session_id}<br>
      Order processed at: ${orderDate}
    </p>
  `;

  const mailOptions = {
    from: process.env.EMAIL_USER || 'sisters806@gmail.com',
    to: RESTAURANT_EMAIL, // This ensures it goes to sisters806@gmail.com
    subject: `🍽️ New Order #${order.id} - $${orderTotal} from ${order.customer_name}`,
    html: emailContent
  };

  if (emailTransporter) {
    try {
      // Try to send real email first
      await emailTransporter.sendMail(mailOptions);
      console.log(`✅ EMAIL SENT SUCCESSFULLY to ${RESTAURANT_EMAIL} for order ${order.id}`);
      return;
    } catch (error) {
      console.log(`❌ Email sending failed (${error.message}), showing preview instead:`);
    }
  }
  
  // Show preview in console (either no transporter or email failed)
  console.log(`
📧 EMAIL PREVIEW (Would be sent to: ${RESTAURANT_EMAIL})
═══════════════════════════════════════
Subject: ${mailOptions.subject}

Order Details:
- Order ID: ${order.id}
- Customer: ${order.customer_name}
- Phone: ${order.customer_phone}
- Email: ${order.customer_email}
- Pickup Time: ${order.pickup_time}
- Total: $${orderTotal}
- Time: ${orderDate}

${order.items && order.items.length > 0 ? `Items: ${order.items.join(', ')}` : ''}
${order.notes ? `Notes: ${order.notes}` : ''}

Next Steps:
1. Prepare the order for pickup at: ${order.pickup_time}
2. Contact customer: ${order.customer_phone}
3. Contact customer when order is ready
═══════════════════════════════════════
  `);
}

// Simple SMS notification function for development
async function sendOrderNotificationSMS(order) {
  const orderTotal = (order.amount_total / 100).toFixed(2);
  
  console.log(`
📱 SMS NOTIFICATION (Development Mode)
═══════════════════════════════════════
To: Restaurant Phone
Message: 🍽️ NEW ORDER - Sisters Cafe
Order #${order.id}
Customer: ${order.customer_name}
Phone: ${order.customer_phone}
Total: $${orderTotal}
Time: ${new Date(order.created_at).toLocaleTimeString()}

Please prepare order and contact customer if needed.
═══════════════════════════════════════
  `);
}

// Customer SMS notification for development
async function sendCustomerNotificationSMS(order, message) {
  if (!order.sms_notifications || !order.customer_phone) {
    return;
  }
  
  console.log(`
📱 CUSTOMER SMS (Development Mode)
═══════════════════════════════════════
To: ${order.customer_phone}
Message: Sisters Cafe: ${message}
═══════════════════════════════════════
  `);
}

// API Handlers
function ordersHandler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  if (req.method === 'GET') {
    const sortedOrders = orders.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify(sortedOrders));
  } else {
    res.writeHead(405, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Method not allowed' }));
  }
}

async function addOrderHandler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  if (req.method !== 'POST') {
    res.writeHead(405, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Method not allowed' }));
    return;
  }

  try {
    const order = req.body;
    
    if (!order.id || !order.customer_name || !order.amount_total) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Missing required order fields' }));
      return;
    }
    
    order.is_demo = true;
    order.created_at = order.created_at || new Date().toISOString();
    order.updated_at = new Date().toISOString();
    
    orders.push(order);
    
    console.log(`Demo order created: ${order.id} for ${order.customer_name} ($${(order.amount_total / 100).toFixed(2)})`);
    
    // Send notifications for demo orders
    try {
      await sendOrderNotificationEmail(order);
      await sendOrderNotificationSMS(order);
      
      if (order.sms_notifications && order.customer_phone) {
        await sendCustomerNotificationSMS(order, `Thank you for your order #${order.id}! We've received your order for $${(order.amount_total / 100).toFixed(2)} and will start preparing it shortly. You'll receive updates via SMS.`);
      }
      
      console.log(`✅ All notifications sent for order ${order.id}`);
    } catch (error) {
      console.error('❌ Error sending notifications:', error);
    }
    
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ 
      success: true, 
      order: order,
      message: 'Demo order created successfully with notifications sent'
    }));
    
  } catch (error) {
    console.error('Error creating demo order:', error);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Internal server error' }));
  }
}

function clearOrdersHandler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  if (req.method !== 'POST') {
    res.writeHead(405, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Method not allowed' }));
    return;
  }

  const clearedCount = orders.length;
  orders = [];
  
  console.log(`Cleared ${clearedCount} orders`);
  
  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ 
    success: true, 
    message: `Cleared ${clearedCount} orders`,
    cleared_count: clearedCount
  }));
}

function statusHandler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  if (req.method !== 'POST') {
    res.writeHead(405, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Method not allowed' }));
    return;
  }

  try {
    const orderId = req.query.id;
    const { status } = req.body;

    if (!orderId || !status) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Order ID and status are required' }));
      return;
    }

    const order = orders.find(o => o.id === orderId);
    
    if (!order) {
      res.writeHead(404, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Order not found' }));
      return;
    }

    order.status = status;
    order.updated_at = new Date().toISOString();

    console.log(`Order ${orderId} status updated to: ${status}`);

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ success: true, order }));

  } catch (error) {
    console.error('Error updating order status:', error);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Internal server error' }));
  }
}

const PORT = 3001;
const ROOT_DIR = __dirname;

// MIME types
const mimeTypes = {
  '.html': 'text/html',
  '.js': 'text/javascript',
  '.css': 'text/css',
  '.json': 'application/json',
  '.png': 'image/png',
  '.jpg': 'image/jpg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml',
  '.ico': 'image/x-icon'
};

function getMimeType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  return mimeTypes[ext] || 'application/octet-stream';
}

function serveStaticFile(res, filePath) {
  const fullPath = path.join(ROOT_DIR, filePath);
  
  fs.readFile(fullPath, (err, data) => {
    if (err) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('File not found');
      return;
    }
    
    const mimeType = getMimeType(fullPath);
    res.writeHead(200, { 'Content-Type': mimeType });
    res.end(data);
  });
}

function handleAPIRequest(req, res, pathname) {
  // Set CORS headers for all API requests
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  
  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  // Parse request body for POST requests
  if (req.method === 'POST') {
    let body = '';
    req.on('data', chunk => {
      body += chunk.toString();
    });
    req.on('end', () => {
      try {
        req.body = JSON.parse(body);
      } catch (e) {
        req.body = {};
      }
      routeAPIRequest(req, res, pathname);
    });
  } else {
    routeAPIRequest(req, res, pathname);
  }
}

function routeAPIRequest(req, res, pathname) {
  try {
    if (pathname === '/api/orders') {
      ordersHandler(req, res);
    } else if (pathname === '/api/demo/add-order') {
      addOrderHandler(req, res);
    } else if (pathname === '/api/demo/clear-orders') {
      clearOrdersHandler(req, res);
    } else if (pathname.match(/^\/api\/orders\/[^\/]+\/status$/)) {
      // Extract order ID from path
      const orderId = pathname.split('/')[3];
      req.query = { id: orderId };
      statusHandler(req, res);
    } else if (pathname === '/api/connect/accounts') {
      // Handle Stripe Connect accounts API
      handleConnectAPI(req, res, 'accounts');
    } else if (pathname === '/api/connect/account-links') {
      // Handle Stripe Connect account links API
      handleConnectAPI(req, res, 'account-links');
    } else if (pathname === '/api/connect/products') {
      // Handle Stripe Connect products API
      handleConnectAPI(req, res, 'products');
    } else if (pathname === '/api/connect/checkout') {
      // Handle Stripe Connect checkout API
      handleConnectAPI(req, res, 'checkout');
    } else if (pathname === '/api/create-checkout-session') {
      // Handle regular Stripe checkout session creation
      handleStripeCheckout(req, res);
    } else if (pathname === '/api/webhook') {
      // Handle Stripe webhook
      handleStripeWebhook(req, res);
    } else {
      res.writeHead(404, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'API endpoint not found' }));
    }
  } catch (error) {
    console.error('API Error:', error);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Internal server error' }));
  }
}

/**
 * Handle regular Stripe checkout session creation
 */
async function handleStripeCheckout(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    res.writeHead(200);
    res.end();
    return;
  }

  if (req.method !== 'POST') {
    res.writeHead(405, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: 'Method not allowed' }));
    return;
  }

  try {
    // Use the real Stripe API module
    const modulePath = path.join(__dirname, 'api', 'create-checkout-session.js');

    if (!fs.existsSync(modulePath)) {
      res.writeHead(404, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Checkout module not found' }));
      return;
    }

    const module = await import(`file://${modulePath}`);
    const handler = module.default;

    if (typeof handler !== 'function') {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Invalid checkout module' }));
      return;
    }

    // Add headers property to req for the Stripe module
    req.headers = req.headers || {};
    req.headers['x-forwarded-proto'] = 'http';
    req.headers['host'] = `localhost:${PORT}`;

    await handler(req, res);

  } catch (error) {
    console.error('Stripe Checkout Error:', error);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      error: 'Checkout session error',
      message: error.message
    }));
  }
}

/**
 * Handle Stripe webhook
 */
async function handleStripeWebhook(req, res) {
  try {
    // Dynamically import the webhook module
    const modulePath = path.join(__dirname, 'api', 'webhook.js');
    
    if (!fs.existsSync(modulePath)) {
      res.writeHead(404, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Webhook module not found' }));
      return;
    }

    const module = await import(`file://${modulePath}`);
    const handler = module.default;

    if (typeof handler !== 'function') {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Invalid webhook module' }));
      return;
    }

    await handler(req, res);

  } catch (error) {
    console.error('Stripe Webhook Error:', error);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ 
      error: 'Webhook error',
      message: error.message 
    }));
  }
}

/**
 * Handle Stripe Connect API requests by dynamically importing the appropriate module
 * This allows us to use ES modules in a CommonJS environment
 */
async function handleConnectAPI(req, res, apiType) {
  try {
    // Parse query parameters for GET requests
    if (req.method === 'GET') {
      const parsedUrl = url.parse(req.url, true);
      req.query = parsedUrl.query;
    }

    // Dynamically import the appropriate Connect API module
    const modulePath = path.join(__dirname, 'api', 'connect', `${apiType}.js`);
    
    // Check if the module file exists
    if (!fs.existsSync(modulePath)) {
      res.writeHead(404, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: `Connect API module not found: ${apiType}` }));
      return;
    }

    // Import the module dynamically
    const module = await import(`file://${modulePath}`);
    const handler = module.default;

    if (typeof handler !== 'function') {
      res.writeHead(500, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: `Invalid Connect API module: ${apiType}` }));
      return;
    }

    // Call the handler with req and res
    await handler(req, res);

  } catch (error) {
    console.error(`Connect API Error (${apiType}):`, error);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ 
      error: 'Connect API error',
      message: error.message 
    }));
  }
}

const server = http.createServer((req, res) => {
  const parsedUrl = url.parse(req.url, true);
  const pathname = parsedUrl.pathname;
  
  console.log(`${req.method} ${pathname}`);
  
  // Handle API requests
  if (pathname.startsWith('/api/')) {
    handleAPIRequest(req, res, pathname);
    return;
  }
  
  // Handle static files
  let filePath = pathname;
  
  // Default to index.html for root
  if (filePath === '/') {
    filePath = '/index.html';
  }
  
  // Remove leading slash
  if (filePath.startsWith('/')) {
    filePath = filePath.substring(1);
  }
  
  serveStaticFile(res, filePath);
});

server.listen(PORT, () => {
  console.log('🚀 Sisters Cafe Notification Server');
  console.log('═'.repeat(50));
  console.log(`Server running at: http://localhost:${PORT}`);
  console.log('');
  console.log('📋 Available URLs:');
  console.log(`• Main Site: http://localhost:${PORT}/`);
  console.log(`• Connect Dashboard: http://localhost:${PORT}/connect-dashboard.html`);
  console.log(`• Connect Storefront: http://localhost:${PORT}/connect-storefront.html`);
  console.log('');
  console.log('🔧 API Endpoints:');
  console.log(`• GET  /api/orders - List orders`);
  console.log(`• POST /api/demo/add-order - Create demo order (with notifications)`);
  console.log(`• POST /api/demo/clear-orders - Clear all orders`);
  console.log(`• POST /api/webhook - Stripe webhook (handles real orders)`);
  console.log('');
  console.log('🏪 Stripe Connect API:');
  console.log(`• POST /api/connect/accounts - Create connected account`);
  console.log(`• GET  /api/connect/accounts?account_id=xxx - Get account info`);
  console.log(`• POST /api/connect/account-links - Create onboarding links`);
  console.log(`• POST /api/connect/products - Create products`);
  console.log(`• GET  /api/connect/products - List products`);
  console.log(`• POST /api/connect/checkout - Create checkout session`);
  console.log('');
  console.log('📧📱 Notification System:');
  console.log('• Email notifications to: sisters806@gmail.com');
  console.log('• SMS notifications to restaurant phone');
  console.log('• Customer SMS confirmations (if opted in)');
  console.log('• Currently in DEVELOPMENT MODE (console previews)');
  console.log('');
  console.log('🧪 Testing:');
  console.log('1. Create test order: curl -X POST http://localhost:3001/api/demo/add-order \\');
  console.log('   -H "Content-Type: application/json" \\');
  console.log('   -d \'{"id":"TEST123","customer_name":"Test Customer","customer_phone":"555-1234","customer_email":"test@example.com","amount_total":2500,"status":"paid","items":["Test Item"]}\'');
  console.log('2. Check console for notification previews');
  console.log('3. See NOTIFICATION_SETUP.md for production setup');
  console.log('');
  console.log('Press Ctrl+C to stop the server');
});

// Graceful shutdown
process.on('SIGINT', () => {
  console.log('\n👋 Shutting down server...');
  server.close(() => {
    console.log('Server stopped');
    process.exit(0);
  });
});

// Handle uncaught exceptions
process.on('uncaughtException', (error) => {
  console.error('Uncaught Exception:', error);
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('Unhandled Rejection at:', promise, 'reason:', reason);
});