import Stripe from 'stripe';
import { orders } from './orders.js';
import nodemailer from 'nodemailer';
import { Readable } from 'stream';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
const endpointSecret = process.env.STRIPE_WEBHOOK_SECRET;

// Email configuration
const emailTransporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER || 'your-email@gmail.com',
    pass: process.env.EMAIL_APP_PASSWORD || 'your-app-password'
  }
});

// SMS configuration (using Twilio)
const twilioClient = process.env.TWILIO_ACCOUNT_SID ? 
  require('twilio')(process.env.TWILIO_ACCOUNT_SID, process.env.TWILIO_AUTH_TOKEN) : 
  null;

// Restaurant notification settings
const RESTAURANT_EMAIL = 'sisters806@gmail.com';
const RESTAURANT_PHONE = process.env.RESTAURANT_PHONE || '+1234567890'; // Set your restaurant phone number

// Email notification function
async function sendOrderEmail(order) {
  try {
    const orderTotal = (order.amount_total / 100).toFixed(2);
    const orderDate = new Date(order.created_at).toLocaleString();
    
    const emailContent = `
      <h2>🍽️ New Order Received - Sisters Cafe</h2>
      
      <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
        <h3>Order Details</h3>
        <p><strong>Order ID:</strong> ${order.id}</p>
        <p><strong>Customer:</strong> ${order.customer_name}</p>
        <p><strong>Phone:</strong> ${order.customer_phone}</p>
        <p><strong>Email:</strong> ${order.customer_email}</p>
        <p><strong>Pickup Time:</strong> ${order.pickup_time}</p>
        <p><strong>Total Amount:</strong> $${orderTotal}</p>
        <p><strong>Order Time:</strong> ${orderDate}</p>
        <p><strong>Payment Status:</strong> ✅ ${order.status.toUpperCase()}</p>
      </div>
      
      ${order.items && order.items.length > 0 ? `
        <div style="background: #e9ecef; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3>🛒 Items Ordered</h3>
          <ul style="margin: 0; padding-left: 20px;">
            ${order.items.map(item => `<li style="margin-bottom: 5px;">${item}</li>`).join('')}
          </ul>
        </div>
      ` : ''}
      
      ${order.notes ? `
        <div style="background: #fff3cd; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3>📝 Special Instructions</h3>
          <p style="margin: 0;">${order.notes}</p>
        </div>
      ` : ''}
      
      <div style="background: #d1ecf1; padding: 20px; border-radius: 8px; margin: 20px 0;">
        <h3>📋 Next Steps</h3>
        <ol style="margin: 0; padding-left: 20px;">
          <li>Prepare the order for pickup at: <strong>${order.pickup_time}</strong></li>
          <li>Contact customer if needed: <a href="tel:${order.customer_phone}" style="color: #007bff;">${order.customer_phone}</a></li>
          <li>Email customer at: <a href="mailto:${order.customer_email}" style="color: #007bff;">${order.customer_email}</a></li>
          <li>Contact customer when order is ready for pickup</li>
        </ol>
      </div>
      
      <hr>
      <p style="color: #6c757d; font-size: 12px;">
        This email was automatically generated by Sisters Cafe online ordering system.<br>
        Stripe Session ID: ${order.stripe_session_id}<br>
        Order processed at: ${orderDate}
      </p>
    `;

    const mailOptions = {
      from: process.env.EMAIL_USER || 'noreply@sisterscafe.com',
      to: RESTAURANT_EMAIL,
      subject: `🍽️ New Order #${order.id} - $${orderTotal} from ${order.customer_name}`,
      html: emailContent
    };

    await emailTransporter.sendMail(mailOptions);
    console.log(`✅ Order email sent to ${RESTAURANT_EMAIL} for order ${order.id}`);
    
  } catch (error) {
    console.error('❌ Failed to send order email:', error);
  }
}

// SMS notification function
async function sendOrderSMS(order) {
  if (!twilioClient) {
    console.log('⚠️ Twilio not configured, skipping SMS notification');
    return;
  }
  
  try {
    const orderTotal = (order.amount_total / 100).toFixed(2);
    
    const smsMessage = `🍽️ NEW ORDER - Sisters Cafe
Order #${order.id}
Customer: ${order.customer_name}
Phone: ${order.customer_phone}
Total: $${orderTotal}
Time: ${new Date(order.created_at).toLocaleTimeString()}

Please prepare order and contact customer if needed.`;

    await twilioClient.messages.create({
      body: smsMessage,
      from: process.env.TWILIO_PHONE_NUMBER,
      to: RESTAURANT_PHONE
    });
    
    console.log(`✅ Order SMS sent to ${RESTAURANT_PHONE} for order ${order.id}`);
    
  } catch (error) {
    console.error('❌ Failed to send order SMS:', error);
  }
}

// Customer SMS notification function (if they opted in)
async function sendCustomerSMS(order, message) {
  if (!twilioClient || !order.sms_notifications || !order.customer_phone) {
    return;
  }
  
  try {
    await twilioClient.messages.create({
      body: `Sisters Cafe: ${message}`,
      from: process.env.TWILIO_PHONE_NUMBER,
      to: order.customer_phone
    });
    
    console.log(`✅ Customer SMS sent to ${order.customer_phone} for order ${order.id}`);
    
  } catch (error) {
    console.error('❌ Failed to send customer SMS:', error);
  }
}

async function getRawBody(req) {
  if (req.rawBody) {
    return req.rawBody;
  }

  const chunks = [];

  for await (const chunk of req instanceof Readable ? req : Readable.from(req)) {
    chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
  }

  return Buffer.concat(chunks);
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  const sig = req.headers['stripe-signature'];
  let event;

  try {
    // Get raw body for webhook verification
    const rawBody = await getRawBody(req);
    event = stripe.webhooks.constructEvent(rawBody, sig, endpointSecret);
  } catch (err) {
    console.error('Webhook signature verification failed:', err.message);
    res.status(400).json({ error: 'Webhook signature verification failed' });
    return;
  }

  // Handle the event
  try {
    switch (event.type) {
      case 'checkout.session.completed':
        const session = event.data.object;
        
        // Retrieve line items from the session
        let orderItems = [];
        try {
          const lineItems = await stripe.checkout.sessions.listLineItems(session.id, {
            expand: ['data.price.product']
          });
          
          orderItems = lineItems.data
            .filter(item => !item.description || !item.description.includes('Tax')) // Filter out tax items
            .map(item => {
              const productName = item.price?.product?.name || item.description || 'Unknown Item';
              return `${productName} x ${item.quantity}`;
            });
        } catch (error) {
          console.error('Error retrieving line items:', error);
          orderItems = ['Items details unavailable'];
        }
        
        // Save order to memory (in production, save to database)
        const order = {
          id: `SC${Date.now()}${Math.floor(Math.random() * 1000)}`,
          stripe_session_id: session.id,
          customer_name: session.metadata?.customer_name || '',
          customer_phone: session.metadata?.customer_phone || '',
          customer_email: session.customer_email || '',
          pickup_time: session.metadata?.pickup_time || 'Not specified',
          amount_total: session.amount_total,
          status: 'paid',
          created_at: new Date().toISOString(),
          items: orderItems,
          notes: session.metadata?.order_notes || ''
        };
        
        orders.push(order);
        console.log(`Order saved: ${order.id} for ${order.customer_name}`);
        
        // Send automatic notifications
        try {
          // Send email notification to restaurant
          await sendOrderEmail(order);
          
          // Send SMS notification to restaurant
          await sendOrderSMS(order);
          
          // Send confirmation SMS to customer (if they opted in)
          if (order.sms_notifications && order.customer_phone) {
            await sendCustomerSMS(order, `Thank you for your order #${order.id}! We've received your order for $${(order.amount_total / 100).toFixed(2)} and will start preparing it shortly. You'll receive updates via SMS.`);
          }
          
          console.log(`✅ All notifications sent for order ${order.id}`);
          
        } catch (notificationError) {
          console.error('❌ Error sending notifications:', notificationError);
          // Don't fail the webhook if notifications fail
        }
        
        break;
        
      case 'payment_intent.succeeded':
        const paymentIntent = event.data.object;
        console.log(`Payment succeeded: ${paymentIntent.id}`);
        break;
        
      default:
        console.log(`Unhandled event type: ${event.type}`);
    }

    res.status(200).json({ received: true });
    
  } catch (error) {
    console.error('Error processing webhook:', error);
    res.status(500).json({ error: 'Webhook processing failed' });
  }
}

// Configure to receive raw body for webhook verification
export const config = {
  api: {
    bodyParser: false,
  },
};
